import type { CaseRecord, InspectionStage, TransactionPlan } from "./types";

const inspectionTemplate: InspectionStage[] = [
  {
    id: "before",
    title: "看车前 / Before you go",
    checks: [
      { id: "vin", label: "VIN 与报告、车身一致", status: "pass" },
      { id: "title", label: "原始 title 与卖家身份证姓名一致", status: "unknown" },
      { id: "cold", label: "卖家同意保留冷车状态", status: "pass" },
      { id: "ppi-ok", label: "卖家允许独立 PPI", status: "pass" },
    ],
  },
  {
    id: "exterior",
    title: "外观结构 / Exterior & structure",
    checks: [
      { id: "gaps", label: "面板缝隙、色差、漆雾", status: "unknown" },
      { id: "glass", label: "玻璃日期、裂纹和密封", status: "unknown" },
      { id: "tires", label: "轮胎 DOT、磨损和四条匹配", status: "unknown" },
      { id: "rust", label: "底盘、门槛和副车架锈蚀", status: "unknown" },
    ],
  },
  {
    id: "interior",
    title: "内饰电气 / Interior & electrical",
    checks: [
      { id: "lamp-test", label: "MIL / ABS / SRS 灯自检", status: "unknown" },
      { id: "water", label: "地毯、天窗和备胎槽无水迹", status: "unknown" },
      { id: "accessories", label: "空调、门窗、摄像头和钥匙", status: "unknown" },
    ],
  },
  {
    id: "drive",
    title: "冷启动试驾 / Cold start & drive",
    checks: [
      { id: "start", label: "冷启动无烟、抖动、异响", status: "unknown" },
      { id: "temp", label: "完整热车后温度稳定", status: "unknown" },
      { id: "shift", label: "P-R-D 与各挡换挡平顺", status: "unknown" },
      { id: "road", label: "制动、转向、悬挂和高速无异常", status: "unknown" },
    ],
  },
  {
    id: "ppi",
    title: "升举 PPI / Professional inspection",
    checks: [
      { id: "leaks", label: "机油、冷却液、变速箱无渗漏", status: "unknown" },
      { id: "structure", label: "举升检查结构和严重锈蚀", status: "unknown" },
      { id: "cooling", label: "冷却系统压力测试", status: "unknown" },
      { id: "scan", label: "OEM 增强型全模块扫描", status: "unknown" },
    ],
  },
];

const samplePlan: TransactionPlan = {
  decision: "INSPECT",
  verified_as_of: "2026-07-12",
  hard_gates: [
    {
      id: "identity",
      title: "核对卖家身份",
      detail: "驾照姓名、原始 NY title 车主姓名与 VIN 必须一致。",
      status: "verify",
    },
    {
      id: "transport",
      title: "禁止借牌开走",
      detail: "只有保险和 bill of sale 仍不足以上路；使用合法临牌、已登记车牌或拖车。",
      status: "required",
    },
  ],
  tasks: [
    {
      id: "insurance",
      title: "为该 VIN 绑定保险",
      detail: "在车辆上路前取得生效证明，并使用实际 garaging address。",
      status: "required",
    },
    {
      id: "sign",
      title: "正确签署 NY title 与 bill of sale",
      detail: "核对里程、成交价、日期；任何涂改都先咨询 DMV。",
      status: "required",
    },
    {
      id: "nj-mvc",
      title: "在 NJ MVC 完成 title / registration",
      detail: "携带原始 title、身份证明、保险、购车文件并缴纳适用税费。",
      status: "verify",
      official_url: "https://www.nj.gov/mvc/vehicles/transowner.htm",
    },
  ],
};

export const demoCases: CaseRecord[] = [
  {
    id: "demo-corolla-e170",
    name: "Synthetic demo · 2017 Toyota Corolla LE",
    status: "NEGOTIATING",
    decision: "NEGOTIATE",
    vehicle: {
      vin: "1TESTCAR000000001",
      year: 2017,
      make: "Toyota",
      model: "Corolla",
      trim: "LE",
      generation: "E170",
      platform: "E170",
      engine: "1.8L 2ZR-FE I4",
      transmission: "CVT",
      drivetrain: "FWD",
      fuel_type: "gasoline",
    },
    listing: {
      id: "listing-corolla",
      title: "2017 Toyota Corolla LE — synthetic demo",
      asking_price: 8200,
      mileage: 88400,
      currency: "USD",
      location: "Example City, NJ",
      seller_type: "private",
      channel: "facebook_marketplace",
      is_target: true,
      source_url: "https://example.com/listings/synthetic-corolla",
      captured_at: "2026-07-12T10:35:00-04:00",
    },
    coverage_percent: 74,
    risk_axes: [
      { id: "price", label: "价格吸引力", level: "low", note: "$7,700 属合成可比区间，仍需以 PPI 通过为条件" },
      { id: "mechanical", label: "机械风险", level: "moderate", note: "88k miles；冷却系统、CV boots 与轮胎年龄尚未检查" },
      { id: "history", label: "历史记录", level: "low", note: "合成示例报告未列出事故，但维修时间线仍有空档" },
      { id: "title", label: "产权交易", level: "unknown", note: "Clean title 声明尚未与原件及身份证核对" },
      { id: "evidence", label: "证据覆盖", level: "moderate", note: "已有合成历史摘要与卖家解释；缺 PPI 和 title 原件" },
    ],
    findings: [
      {
        id: "f-readiness",
        title: "一次排放 readiness 重置",
        summary: "合成卖家说明称更换电瓶后 readiness 被重置；目前只能视为待现场核验的解释。",
        level: "moderate",
        status: "possible",
        category: "history",
        evidence_ids: ["e-history", "e-chat"],
        next_check: "现场检查 readiness、stored/pending/permanent codes 与电瓶 CCA。",
        exposure_low: 0,
        exposure_high: 500,
      },
      {
        id: "f-brakes",
        title: "近期完成前刹车保养",
        summary: "合成记录称已更换前刹车片；等待发票确认零件与施工范围。",
        level: "low",
        status: "possible",
        category: "inspection",
        evidence_ids: ["e-chat", "e-history"],
        next_check: "查看发票并在 PPI 中测量制动与检查卡钳。",
      },
      {
        id: "f-cooling",
        title: "冷却系统状态未知",
        summary: "无故障码不等于已证明无泄漏；普通 OBD 不能替代冷车目检和压力测试。",
        level: "moderate",
        status: "unknown",
        category: "mechanical",
        evidence_ids: [],
        next_check: "冷车目检并做冷却系统压力测试。",
        exposure_low: 450,
        exposure_high: 1800,
      },
    ],
    evidence: [
      { id: "e-listing", label: "Synthetic listing snapshot", source: "Demo fixture", captured_at: "2026-07-12", status: "verified" },
      { id: "e-history", label: "Synthetic vehicle-history summary", source: "Demo fixture", captured_at: "2026-07-12", reference: "sample events", status: "verified" },
      { id: "e-chat", label: "Synthetic seller explanation", source: "Demo fixture", captured_at: "2026-07-12", status: "unverified" },
    ],
    valuation: {
      market_label: "asking-price range",
      asking_price: 8200,
      market_median: 8450,
      q1: 7900,
      q3: 9100,
      sample_count: 9,
      confidence: "medium",
      target: 7600,
      opening: 7200,
      ceiling: 7770,
      repair_adjustment: 300,
      evidence_reserve: 423,
    },
    inspections: structuredClone(inspectionTemplate),
    transaction_plan: samplePlan,
    diagnostics: {
      coverage: ["Generic powertrain", "Readiness monitors", "Pending/permanent DTC"],
      not_covered: ["ABS", "SRS", "Body modules", "Toyota manufacturer modules"],
      readiness: "unknown",
      codes: [],
      note: "尚未现场扫描；无代码不能替代冷却压力测试或 PPI。",
    },
    unresolved_planning_exposure: [600, 1900],
    updated_at: "2026-07-12T10:35:00-04:00",
  },
  {
    id: "demo-fit",
    name: "2013 Honda Fit Sport",
    status: "NEEDS_DATA",
    decision: "INSPECT",
    vehicle: {
      year: 2013,
      make: "Honda",
      model: "Fit",
      trim: "Sport",
      generation: "GE8",
      engine: "1.5L L15A7 I4",
      transmission: "5-speed automatic",
      drivetrain: "FWD",
      fuel_type: "gasoline",
    },
    listing: {
      id: "listing-fit",
      title: "2013 Honda Fit Sport",
      asking_price: 4800,
      mileage: 168000,
      currency: "USD",
      location: "Example City, CT",
      seller_type: "private",
      channel: "facebook_marketplace",
      captured_at: "2026-07-12",
    },
    coverage_percent: 28,
    risk_axes: [
      { id: "price", label: "价格吸引力", level: "unknown", note: "可比车样本不足" },
      { id: "mechanical", label: "机械风险", level: "unknown", note: "没有 OBD、保养记录或 PPI" },
      { id: "history", label: "历史记录", level: "unknown", note: "尚未导入车辆历史报告" },
      { id: "title", label: "产权交易", level: "unknown", note: "VIN 与 title 未核对" },
      { id: "evidence", label: "证据覆盖", level: "high", note: "仅有 listing；不得给出最终最高价" },
    ],
    findings: [],
    evidence: [],
    valuation: { market_label: "asking-price range", asking_price: 4800, sample_count: 2, confidence: "low" },
    inspections: structuredClone(inspectionTemplate).map((stage) => ({
      ...stage,
      checks: stage.checks.map((check) => ({ ...check, status: "unknown" as const })),
    })),
    transaction_plan: { decision: "STOP", verified_as_of: "2026-07-12", hard_gates: [], tasks: [] },
    diagnostics: { coverage: [], not_covered: ["All modules"], readiness: "unknown", codes: [], note: "尚无扫描。" },
    unresolved_planning_exposure: [500, 1800],
    updated_at: "2026-07-12T09:00:00-04:00",
  },
];
