#!/usr/bin/env python3
"""Safe, no-key-required local quickstart for OpenCarDueDiligence.

The script intentionally uses only the Python standard library.  It prepares a
private ``.env`` file, starts the loopback-only Docker Compose stack, waits for
both HTTP entry points, and opens the buyer workspace.  It never enables an LLM
provider or prints generated secrets.
"""

from __future__ import annotations

import argparse
import base64
import os
from pathlib import Path
import re
import secrets
import shutil
import subprocess
import sys
import time
from typing import Sequence
from urllib.error import HTTPError, URLError
from urllib.request import urlopen
import webbrowser


REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_KEY_PATTERN = re.compile(r"^(?P<prefix>\s*(?:export\s+)?)(?P<key>[A-Za-z_][A-Za-z0-9_]*)=(?P<value>.*)$")
DEFAULT_WEB_PORT = 3000
DEFAULT_API_PORT = 8000
DEFAULT_WAIT_TIMEOUT = 300
DOCKER_INSTALL_HELP = (
    "Install the free Docker Engine, or use free Colima with the Docker CLI and Compose plugin. "
    "Docker Desktop is optional."
)
LEGACY_LOCAL_VOLUMES = ("opencarduediligence_valkey-data",)


class QuickstartError(RuntimeError):
    """An actionable quickstart failure."""


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def env_values(text: str) -> dict[str, str]:
    """Return the last active value for each simple dotenv assignment."""

    values: dict[str, str] = {}
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        match = ENV_KEY_PATTERN.match(line)
        if match:
            values[match.group("key")] = _unquote(match.group("value"))
    return values


def set_env_value(text: str, key: str, value: str, *, force: bool = True) -> str:
    """Set the final active assignment for ``key`` without exposing its value."""

    lines = text.splitlines()
    matching_indexes = []
    for index, line in enumerate(lines):
        match = ENV_KEY_PATTERN.match(line)
        if match and match.group("key") == key:
            matching_indexes.append(index)
    if matching_indexes:
        index = matching_indexes[-1]
        current = _unquote(ENV_KEY_PATTERN.match(lines[index]).group("value"))  # type: ignore[union-attr]
        if force or not current:
            lines[index] = f"{key}={value}"
    else:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def _decode_worker_key(value: str) -> bytes:
    try:
        decoded = base64.urlsafe_b64decode(value.encode("ascii"))
    except (ValueError, UnicodeEncodeError) as exc:
        raise QuickstartError(
            "OCDD_WORKER_ENVELOPE_KEY in .env is not valid URL-safe base64. "
            "Remove that line and run prepare again."
        ) from exc
    if len(decoded) != 32:
        raise QuickstartError(
            "OCDD_WORKER_ENVELOPE_KEY in .env must decode to exactly 32 bytes. "
            "Remove that line and run prepare again."
        )
    return decoded


def _port(value: str | None, fallback: int, label: str) -> int:
    try:
        parsed = int(value) if value else fallback
    except ValueError as exc:
        raise QuickstartError(f"{label} must be an integer between 1 and 65535") from exc
    if not 1 <= parsed <= 65535:
        raise QuickstartError(f"{label} must be between 1 and 65535")
    return parsed


def prepare_environment(
    repo_root: Path = REPO_ROOT,
    *,
    web_port: int | None = None,
    api_port: int | None = None,
) -> tuple[int, int, bool]:
    """Create or harden the ignored local dotenv file.

    Existing non-empty secrets and optional provider configuration are never
    overwritten.  API and CORS settings are always reset to loopback-only
    values: this command is the safe local path and must never inherit a stale
    cloud endpoint or remote browser origin from an older ``.env`` file.
    """

    env_path = repo_root / ".env"
    example_path = repo_root / ".env.example"
    if env_path.exists():
        text = env_path.read_text(encoding="utf-8")
        created = False
    else:
        if not example_path.exists():
            raise QuickstartError(f"missing environment template: {example_path}")
        text = example_path.read_text(encoding="utf-8")
        text = (
            "# Generated by scripts/quickstart.py. This ignored file contains local secrets.\n"
            "# Do not commit or share it.\n\n"
            + text
        )
        created = True

    values = env_values(text)
    selected_web_port = _port(
        str(web_port) if web_port is not None else values.get("OCDD_WEB_PORT"),
        DEFAULT_WEB_PORT,
        "web port",
    )
    selected_api_port = _port(
        str(api_port) if api_port is not None else values.get("OCDD_API_PORT"),
        DEFAULT_API_PORT,
        "API port",
    )

    worker_key = values.get("OCDD_WORKER_ENVELOPE_KEY", "")
    if worker_key:
        _decode_worker_key(worker_key)
    else:
        worker_key = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("ascii")
        text = set_env_value(text, "OCDD_WORKER_ENVELOPE_KEY", worker_key)

    if not values.get("OCDD_OBD_BRIDGE_TOKEN", ""):
        text = set_env_value(text, "OCDD_OBD_BRIDGE_TOKEN", secrets.token_urlsafe(32))

    text = set_env_value(text, "OCDD_WEB_PORT", str(selected_web_port))
    text = set_env_value(text, "OCDD_API_PORT", str(selected_api_port))

    api_url = f"http://localhost:{selected_api_port}"
    for key in ("OCDD_API_URL", "NEXT_PUBLIC_OCDD_API_URL"):
        text = set_env_value(text, key, api_url)

    origins = (
        f"http://localhost:{selected_web_port}",
        f"http://127.0.0.1:{selected_web_port}",
    )
    text = set_env_value(text, "OCDD_CORS_ORIGINS", ",".join(origins))

    if not env_values(text).get("OCDD_LLM_PROVIDER"):
        text = set_env_value(text, "OCDD_LLM_PROVIDER", "disabled")

    temporary_path = env_path.with_name(f".{env_path.name}.tmp-{os.getpid()}")
    try:
        temporary_path.write_text(text, encoding="utf-8")
        try:
            temporary_path.chmod(0o600)
        except OSError:
            # Some Windows filesystems do not implement POSIX permission bits.
            pass
        os.replace(temporary_path, env_path)
        try:
            env_path.chmod(0o600)
        except OSError:
            pass
    finally:
        temporary_path.unlink(missing_ok=True)

    return selected_web_port, selected_api_port, created


def compose_command(*arguments: str, repo_root: Path = REPO_ROOT) -> list[str]:
    """Return a Compose command pinned to this checkout's safe local manifest.

    Compose otherwise accepts inherited ``COMPOSE_FILE``/project settings and
    automatically discovers override files. The public quickstart must not let
    unrelated shell configuration replace the loopback-only stack.
    """

    return [
        "docker",
        "compose",
        "--project-name",
        "opencarduediligence",
        "--project-directory",
        str(repo_root),
        "--env-file",
        str(repo_root / ".env"),
        "--file",
        str(repo_root / "docker-compose.yml"),
        *arguments,
    ]


def sanitized_subprocess_environment() -> dict[str, str]:
    """Remove inherited app/Compose overrides while retaining Docker context."""

    environment = os.environ.copy()
    for key in list(environment):
        if key.startswith(("COMPOSE_", "OCDD_", "NEXT_PUBLIC_OCDD_")):
            environment.pop(key, None)
    return environment


def run_command(
    command: Sequence[str],
    *,
    repo_root: Path = REPO_ROOT,
    check: bool = True,
    capture_output: bool = False,
) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            list(command),
            cwd=repo_root,
            env=sanitized_subprocess_environment(),
            check=check,
            text=True,
            capture_output=capture_output,
        )
    except FileNotFoundError as exc:
        raise QuickstartError(f"Docker was not found. {DOCKER_INSTALL_HELP}") from exc
    except subprocess.CalledProcessError as exc:
        rendered = " ".join(command)
        raise QuickstartError(f"command failed ({exc.returncode}): {rendered}") from exc


def require_docker(repo_root: Path = REPO_ROOT) -> None:
    if shutil.which("docker") is None:
        raise QuickstartError(f"Docker was not found. {DOCKER_INSTALL_HELP}")
    try:
        run_command(["docker", "version"], repo_root=repo_root, capture_output=True)
        run_command(compose_command("version", repo_root=repo_root), repo_root=repo_root, capture_output=True)
    except QuickstartError as exc:
        raise QuickstartError(f"Docker is installed but not ready. Start its daemon. {DOCKER_INSTALL_HELP}") from exc
    compose_help = run_command(
        compose_command("up", "--help", repo_root=repo_root),
        repo_root=repo_root,
        capture_output=True,
    ).stdout
    if "--wait" not in compose_help or "--wait-timeout" not in compose_help:
        raise QuickstartError(
            "Docker Compose is too old for the safe health-gated quickstart. "
            "Update the Compose v2 plugin to a version whose `docker compose up --help` "
            "lists --wait and --wait-timeout."
        )
    run_command(compose_command("config", "--quiet", repo_root=repo_root), repo_root=repo_root, capture_output=True)


def _healthy(url: str) -> bool:
    try:
        with urlopen(url, timeout=3) as response:  # noqa: S310 - fixed local URLs only
            return 200 <= response.status < 400
    except (HTTPError, URLError, TimeoutError, OSError):
        return False


def wait_for_stack(web_port: int, api_port: int, timeout: int) -> None:
    web_url = f"http://127.0.0.1:{web_port}/"
    api_url = f"http://127.0.0.1:{api_port}/health"
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if _healthy(api_url) and _healthy(web_url):
            return
        time.sleep(1)
    raise QuickstartError(
        f"the local stack did not become reachable within {timeout} seconds. "
        "Run `python3 scripts/quickstart.py status` for container status."
    )


def start(
    repo_root: Path = REPO_ROOT,
    *,
    web_port: int | None = None,
    api_port: int | None = None,
    wait_timeout: int = DEFAULT_WAIT_TIMEOUT,
    open_browser: bool = True,
) -> None:
    selected_web_port, selected_api_port, created = prepare_environment(
        repo_root,
        web_port=web_port,
        api_port=api_port,
    )
    if created:
        print("Prepared a private .env file with fresh random worker and OBD bridge secrets.")
    else:
        print("Using the existing private .env file (secrets were not replaced).")
    print("No API key or paid service is required. LLM explanations remain optional and disabled by default.")
    print("Starting the local-only stack. The first image build can take several minutes...")
    sys.stdout.flush()
    require_docker(repo_root)
    up_arguments = ["up", "--detach", "--remove-orphans", "--build"]
    up_arguments.extend(["--wait", "--wait-timeout", str(wait_timeout)])
    run_command(compose_command(*up_arguments, repo_root=repo_root), repo_root=repo_root)
    wait_for_stack(selected_web_port, selected_api_port, wait_timeout)
    workspace_url = f"http://localhost:{selected_web_port}"
    print(f"\nOpenCarDueDiligence is ready: {workspace_url}")
    print("Private data stays in this loopback-only local stack. Stop it with:")
    print("  python3 scripts/quickstart.py stop")
    print("To also delete the local Docker volumes and every local case, use:")
    print("  python3 scripts/quickstart.py stop --delete-data")
    if open_browser and not os.getenv("CI"):
        webbrowser.open(workspace_url, new=2)


def status(repo_root: Path = REPO_ROOT) -> None:
    web_port, api_port, _ = prepare_environment(repo_root)
    require_docker(repo_root)
    run_command(compose_command("ps", repo_root=repo_root), repo_root=repo_root)
    if not (_healthy(f"http://127.0.0.1:{api_port}/health") and _healthy(f"http://127.0.0.1:{web_port}/")):
        raise QuickstartError("one or more local services are not reachable")
    print(f"Healthy: http://localhost:{web_port} (API: http://localhost:{api_port})")


def stop(repo_root: Path = REPO_ROOT, *, delete_data: bool = False) -> None:
    require_docker(repo_root)
    arguments = ["down", "--remove-orphans"]
    if delete_data:
        arguments.append("--volumes")
    run_command(compose_command(*arguments, repo_root=repo_root), repo_root=repo_root)
    if delete_data:
        # A short-lived alpha used a different queue-volume key.  Compose only
        # deletes volumes declared by the current file, so remove that known
        # project-scoped legacy volume after the user explicitly requests a
        # complete local-data deletion.  Absence is expected and ignored.
        existing_legacy_volumes = [
            volume
            for volume in LEGACY_LOCAL_VOLUMES
            if run_command(
                ["docker", "volume", "inspect", volume],
                repo_root=repo_root,
                check=False,
                capture_output=True,
            ).returncode
            == 0
        ]
        if existing_legacy_volumes:
            run_command(
                ["docker", "volume", "rm", *existing_legacy_volumes],
                repo_root=repo_root,
                capture_output=True,
            )
        print("Stopped the stack and deleted its local Docker data volumes.")
    else:
        print("Stopped the stack. Local cases remain in its private Docker volume; artifact blobs are encrypted at rest.")
        print("Use `python3 scripts/quickstart.py stop --delete-data` to delete those volumes.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run OpenCarDueDiligence locally without API keys or paid services.",
    )
    parser.add_argument(
        "command",
        nargs="?",
        choices=("start", "prepare", "status", "stop"),
        default="start",
        help="action to perform (default: start)",
    )
    parser.add_argument("--web-port", type=int, help=f"local web port (default: {DEFAULT_WEB_PORT})")
    parser.add_argument("--api-port", type=int, help=f"local API port (default: {DEFAULT_API_PORT})")
    parser.add_argument("--wait-timeout", type=int, default=DEFAULT_WAIT_TIMEOUT, help="startup timeout in seconds")
    parser.add_argument("--no-open", action="store_true", help="do not open a browser after startup")
    parser.add_argument(
        "--delete-data",
        action="store_true",
        help="with stop, also delete all local OpenCarDueDiligence Docker volumes",
    )
    return parser


def main(argv: Sequence[str] | None = None, *, repo_root: Path = REPO_ROOT) -> int:
    args = build_parser().parse_args(argv)
    if args.wait_timeout < 1:
        raise QuickstartError("--wait-timeout must be at least 1 second")
    if args.command != "stop" and args.delete_data:
        raise QuickstartError("--delete-data is accepted only with the stop command")

    if args.command == "prepare":
        web_port, api_port, created = prepare_environment(
            repo_root,
            web_port=args.web_port,
            api_port=args.api_port,
        )
        action = "Created" if created else "Updated"
        print(f"{action} private .env configuration for web :{web_port} and API :{api_port}.")
        print("No secret value was printed. LLM providers are optional and disabled by default.")
    elif args.command == "status":
        status(repo_root)
    elif args.command == "stop":
        stop(repo_root, delete_data=args.delete_data)
    else:
        start(
            repo_root,
            web_port=args.web_port,
            api_port=args.api_port,
            wait_timeout=args.wait_timeout,
            open_browser=not args.no_open,
        )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except QuickstartError as exc:
        print(f"Quickstart error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
